---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  csslint:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD029:
        enabled: false
  eslint:
    enabled: true
    channel: "eslint-2"
    checks:
      strict:
        enabled: false
  nodesecurity:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - TODO
      - XXX
      - HACK
      - FixMe
      - fixme
ratings:
  paths:
  - "**.js"
  - "**.jsx"
  - "**.html"
  - "**.css"
  - "**.html"
  - "**.md"
