version: "3.5"
services:
  bgr-api:
    build:
      context: .
    depends_on:
      - mongo
    # Placing environment variables for local development
    environment:
      NODE_ENV: 'development'
      MONGO: 'mongodb://mongo/bgrdb'
      LOG_LEVEL: 'debug'
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
  mongo:
    image: mongo:3.4
    volumes:
      - db_data:/data/db

volumes:
  db_data:
    driver: local
